import { Category } from "./types";
import { MarketplaceItem } from "./types";

export const categories: Category[] = [
    { name: 'Today\'s picks', slug: 'home' },
    { name: 'Vehicles', slug: 'vehicles' },
    { name: 'Property Rentals', slug: 'property-rentals' },
    { name: 'Apparel', slug: 'apparel' },
    { name: 'Classifieds', slug: 'classifieds' },
    { name: 'Electronics', slug: 'electronics' },
    { name: 'Entertainment', slug: 'entertainment' },
    { name: 'Family', slug: 'family' },
    { name: 'Free Stuff', slug: 'free-stuff' },
    { name: 'Garden & Outdoor', slug: 'garden-outdoor' },
    { name: 'Hobbies', slug: 'hobbies' },
    { name: 'Home Goods', slug: 'home-goods' },
    { name: 'Home Improvement', slug: 'home-improvement' },
    { name: 'Home Sales', slug: 'home-sales' },
    { name: 'Musical Instruments', slug: 'musical-instruments' },
    { name: 'Office Supplies', slug: 'office-supplies' },
    { name: 'Pet Supplies', slug: 'pet-supplies' },
    { name: 'Sporting Goods', slug: 'sporting-goods' },
    { name: 'Toys & Games', slug: 'toys-games' },
    { name: 'Buy and sell groups', slug: 'buy-sell-groups' },
];

export const mockItems: MarketplaceItem[] = [
    {
        id: '1',
        title: 'Bike 24 inch',
        price: '99',
        location: 'Palo Alto, CA',
        listedTime: '1 hour',
        seller: 'Wei Gu',
        category: 'sporting-goods',
    },
    {
        id: '2',
        title: 'Vintage Camera',
        price: '2,300',
        location: 'Palo Alto, CA',
        listedTime: '2 hours',
        seller: 'John Smith',
        category: 'electronics',
    },
    {
        id: '3',
        title: 'Leather Sofa',
        price: '2,300',
        location: 'Palo Alto, CA',
        listedTime: '3 hours',
        seller: 'Maria Garcia',
        category: 'home-goods',
    },
    {
        id: '4',
        title: 'Gaming Console',
        price: '2,300',
        location: 'Palo Alto, CA',
        listedTime: '4 hours',
        seller: 'Alex Johnson',
        category: 'electronics',
    },
    {
        id: '5',
        title: 'Mountain Bike',
        price: '2,300',
        location: 'Palo Alto, CA',
        listedTime: '5 hours',
        seller: 'Sarah Wilson',
        category: 'sporting-goods',
    },
    {
        id: '6',
        title: 'Dining Table',
        price: '2,300',
        location: 'Palo Alto, CA',
        listedTime: '6 hours',
        seller: 'Michael Brown',
        category: 'home-goods',
    },
    {
        id: '7',
        title: 'Laptop Computer',
        price: '2,300',
        location: 'Palo Alto, CA',
        listedTime: '7 hours',
        seller: 'Emily Davis',
        category: 'electronics',
    },
    {
        id: '8',
        title: 'Tennis Racket',
        price: '2,300',
        location: 'Palo Alto, CA',
        listedTime: '8 hours',
        seller: 'David Miller',
        category: 'sporting-goods',
    },
    {
        id: '9',
        title: 'Coffee Table',
        price: '2,300',
        location: 'Palo Alto, CA',
        listedTime: '9 hours',
        seller: 'Lisa Anderson',
        category: 'home-goods',
    },
    {
        id: '10',
        title: 'Smartphone',
        price: '2,300',
        location: 'Palo Alto, CA',
        listedTime: '10 hours',
        seller: 'Robert Taylor',
        category: 'electronics',
    },
    {
        id: '11',
        title: 'Bookshelf',
        price: '2,300',
        location: 'Palo Alto, CA',
        listedTime: '11 hours',
        seller: 'Jennifer Wilson',
        category: 'home-goods',
    },
    {
        id: '12',
        title: 'Headphones',
        price: '2,300',
        location: 'Palo Alto, CA',
        listedTime: '12 hours',
        seller: 'Christopher Lee',
        category: 'electronics',
    },
    {
        id: '13',
        title: 'Desk Chair',
        price: '2,300',
        location: 'Palo Alto, CA',
        listedTime: '13 hours',
        seller: 'Amanda Clark',
        category: 'home-goods',
    },
    {
        id: '14',
        title: 'Tablet',
        price: '2,300',
        location: 'Palo Alto, CA',
        listedTime: '14 hours',
        seller: 'Kevin Martinez',
        category: 'electronics',
    },
    {
        id: '15',
        title: 'Exercise Bike',
        price: '2,300',
        location: 'Palo Alto, CA',
        listedTime: '15 hours',
        seller: 'Nicole Thompson',
        category: 'sporting-goods',
    },
];